name: hello-world
# действие на которое запускается workflow
on: push

jobs:
  # имя задания
  say-hello:
    # OC для запуска
    runs-on: ubuntu-latest
    # шаги, которые надо выполнить
    steps:
      # экшен, выполняет какую-то задачу
      # checkout – клонирует репозиторий
      - uses: actions/checkout@v3
      # print - hello world!!!
      - run: make say-hello